name: Build AppImage
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update GPG keys for Xenial Security repository
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32

      - name: Set up Qt
        uses: jurplel/install-qt-action@v3
        with:
          qt-version: '6.2.0'

      - name: OpenCV
        run: sudo apt-get install -y libopencv-apps2d libopencv-apps-dev libopencv-dev python3-opencv libgstreamer-opencv1.0-0 gstreamer1.0-opencv opencv-data

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg libavcodec* libavdevice* libavfilter* libavformat* libavutil* libswscale* libffmpeg-ocaml libsdl-kitchensink1 libsdl-kitchensink-dev libffmpeg-ocaml-dev libavbdevice-dev libavcodec-dev libavformat-dev libswscale-dev libavfilder-dev libswresample-dev libswresample4 libavutil-dev  libpostproc-dev gstreamer1.0-libav libpostproc* ffmpegthumbs

      - name: Install v4l2loopback
        run: sudo apt-get install -y v4l2loopback-dkms v4l2loopback-utils

      - name: Install additional Qt dependencies
        run: sudo apt-get install -y libqt6* qt6-*dev

      - name: Build project
        run: |
          rm -rf build
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=AppDir/usr
          make -j $( nproc )
          make INSTALL_ROOT=AppDir/ -j$(nproc) install ; find AppDir/

      - name: Create AppImage
        run: |
          cd build
          wget -c -nv "https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20220822-1/linuxdeploy-x86_64.AppImage"
          chmod a+x linuxdeploy-x86_64.AppImage
          ARCH=x86_64 ./linuxdeploy-x86_64.AppImage --appdir AppDir/ --output appimage --icon-filename AppDir/usr/bin/matrix-linux.png --desktop-file AppDir/usr/share/applications/Matrix.desktop --icon-file  AppDir/usr/bin/matrix-linux.png

      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: appimage
          path: build/Matrix*-x86_64.AppImage
